INSERT INTO `animal` ( `name_animal`)
VALUES
CREATE TABLE animal (
    `id` NUMERIC(3, 1),
    `name_animal` VARCHAR(18) CHARACTER SET utf8,
    `diet_animal` VARCHAR(21) CHARACTER SET utf8,
    `status_animal` VARCHAR(36) CHARACTER SET utf8,
    `family_animal` VARCHAR(9) CHARACTER SET utf8,
    `population_animal` VARCHAR(23) CHARACTER SET utf8,
    `description_animal` VARCHAR(26) CHARACTER SET utf8,
    `nickname_animal` VARCHAR(78) CHARACTER SET utf8,
    `main_picture_animal` VARCHAR(16) CHARACTER SET utf8
);
INSERT INTO animal VALUES
    (0,'Boa constrictor','Carnivore','Préoccupation mineure','Reptile','pas de chiffres fiables','Terrestre + Arboricole','Am Centrale, Am Sud','boaconstrictor'),
    (1,'Bouquetin','Herbivore','Préoccupation mineure','Mammifère','50 000','Terrestre','Europe','bouquetin'),
    (2,'Cacatoès','Omnivore','En danger','Oiseau','43 000-183 000','Aérien','Océanie, Asie','cacatoes'),
    (3,'Caïman','Carnivore','Quasi-menacé','Reptile','1 000 000','Terrestre/Aquatique','Am Sud','caiman'),
    (4,'Caméléon','Omnivore','Quasi-menacé','Reptile','pas de chiffres fiables','Terrestre','Afrique, Asie, Europe','cameleon'),
    (5,'Casoar','Omnivore','Préoccupation mineure','Oiseau','20 000-50 000','Terrestre','Océanie','casoar'),
    (6,'Diable de Tasmanie','Carnivore','En danger','Mammifère','entre 20 000 et 70 000','Terrestre','Océanie','diabledetasmanie'),
    (7,'Dik Dik','Herbivore','Préoccupation mineure','Mammifère','971 000','Terrestre','Afrique','dikdik'),
    (8,'Dragon de Komodo','Carnivore','Vulnérable','Reptile','5 000','Arboricole et terrestre','Asie','dragondekomodo'),
    (9,'Éléphant d''Afrique','Herbivore','Vulnérable','Mammifère','415 000','Terrestre','Afrique','elephantdafrique'),
    (10,'Éléphant d''Asie','Herbivore','En danger','Mammifère','50 000','Terrestre','Asie','elephantdasie'),
    (11,'Fennec','Omnivore','Préoccupation mineure','Mammifère','inconnu','Terrestre','Afrique','fennec'),
    (12,'Girafe','Herbivore','Vulnérable','Mammifère','100 000','Terrestre','Afrique','girafe'),
    (13,'Gorille','Herbivore','Menacé','Mammifère','110 000','Terrestre','Afrique','gorille'),
    (14,'Grand dauphin','Carnivore','Préoccupation mineure','Mammifère','600 000','Aquatique','Entre les tropiques du cancer et du capricorne (Atlantique, Pacifique, Indien)','granddauphin'),
    (15,'Grue Couronnée','Omnivore','Vulnérable','Oiseau','entre 58 000 et 77 000','Terrestre, Aérien','Afrique','gruecouronnee'),
    (16,'Hyène','Carnivore','Préoccupation mineure','Mammifère','27 000-47 000','Terrestre','Afrique, Asie (Moyen-Orient)','hyene'),
    (17,'Kangourou','Herbivore','Préoccupation mineure','Mammifère','34 000 000','Terrestre','Océanie','kangourou'),
    (18,'Koala','Herbivore','Vulnérable','Mammifère','moins de 40 000','Arboricole','Océanie','koala'),
    (19,'Lamantin','Herbivore','Vulnérable','Mammifère','13 000','Aquatique','Afrique, Am Centrale, Am Sud','lamantin'),
    (20,'Léopard des Neiges','Carnivore','Vulnérable','Mammifère','4 080-6 590','Terrestre','Asie','leoparddesneiges'),
    (21,'Loup','Carnivore','Préoccupation mineure','Mammifère','200,000–250,000','Terrestre','Europe, Am Nord, Asie','loup'),
    (22,'Lynx','Carnivore','Préoccupation mineure','Mammifère','10 000','Terrestre','Europe, Asie','lynx'),
    (23,'Manchot Empereur','Carnivore','Quasi-menacé','Oiseau','1 000 000','Terrestre, Aquatique','Antarctique','manchotempereur'),
    (24,'Mandrill','Omnivore','Vulnérable','Mammifère','220','Terrestre ','Afrique','mandrill'),
    (25,'Marmotte des Alpes','Herbivore','Préoccupation mineure','Mammifère','100 000','Terrestre','Europe','marmottedesalpes'),
    (26,'Okapi','Herbivore','En danger','Mammifère','5 000 - 15 000 ','Terrestre','Afrique','okapi'),
    (27,'Orang-outan','Herbivore (frugivore)','Danger critique','Mammifère','environ 60 000','Arboricole','Asie','orangouton'),
    (28,'Orignal','Omnivore','Préoccupation mineure','Mammifère','1 500 000','Terrestre','Am Nord','orignal'),
    (29,'Orque','Carnivore','Données insuffisantes','Mammifère','50 000','Aquatique','Global','orque'),
    (30,'Ours brun','Omnivore','Préoccupation mineure','Mammifère','200 000','Terrestre','Europe, Am Nord','oursbrun'),
    (31,'Ours polaire','Carnivore','Vulnérable','Mammifère','20 000-25 000','Terrestre + Aquatique','Am Nord, Europe, Asie, Océan Glacial Artctique','ourspolaire'),
    (32,'Panda','Herbivore','Vulnérable','Mammifère','1 864','Terrestre','Asie','panda'),
    (33,'Panda roux','Omnivore','En danger','Mammifère','moins de 10 000','Arboricole','Asie','pandaroux'),
    (34,'Pangolin','Omnivore','Danger critique','Mammifère','200 000','Terrestre','Asie, Afrique','pangolin'),
    (35,'Pélican blanc','Carnivore','Préoccupation mineure','Oiseau','17 000','Aérien','Afrique, Asie, Europe','pelicanblanc'),
    (36,'Phoque','Carnivore','Préoccupation mineure','Mammifère','290 000-300 000','Terrestre/Aquatique/Aérien','Europe, Am Nord','phoque'),
    (37,'Poisson-scie','Omnivore','En danger critique d’extinction (CR)','Poisson','Pas de chiffres fiables','Aquatique','Amérique du Nord, Océanie','poissonscie'),
    (38,'Raie Manta','Autre','Vulnérable','Poisson','Pas de chiffres fiables','Aquatique','Entre les tropiques du cancer et du capricorne (Atlantique, Pacifique, Indien)','raiemanta'),
    (39,'Requin-baleine','Autre','En danger','Poisson','2 100','Aquatique','Entre les tropiques du cancer et du capricorne (Atlantique, Pacifique, Indien)','requinbaleine'),
    (40,'Rhinocéros Noir','Herbivore','Danger critique','Mammifère','3 100','Terrestre','Afrique','rhinocerosnoir'),
    (41,'Tigre ','Carnivore','Menacé d''extinction','Mammifère','3 800','Terrestre','Asie','tigre'),
    (42,'Wombat','Herbivore','Préoccupation mineure','Mammifère','60 000-130 000','Terrestre','Océanie','wombat');